/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountryList: typeof import('./src/components/CountryList.vue')['default']
    CountrySelect: typeof import('./src/components/CountrySelect.vue')['default']
    FlagIconsad1x1: typeof import('~icons/flag-icons/ad1x1')['default']
    FlagIconsAd1x1: typeof import('~icons/flag-icons/ad1x1')['default']
    FlagIconsPh4x3: typeof import('~icons/flag-icons/ph4x3')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MdiCode: typeof import('~icons/mdi/code')['default']
  }
}
